repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: k8s/|wizard-web/src/main/java/eu/gaiax/wizard/controller/|wizard-realm.json