name: Test application (test + coverage)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'

permissions:
  id-token: write
  statuses: write
  checks: write
  # may also be read
  contents: write
  pull-requests: write
  actions: write

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v3
        if: success() || failure()
        with:
          dotnet-version: 6.x
          dotnet-quality: 'ga'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test app
        run: ./gradlew test

      - name: Get coverage
        if: success() || failure()
        run: ./gradlew jacocoTestReport

      - name: Generate test report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test results
          path: 'build/test-results/test/*.xml'
          reporter: java-junit
          fail-on-error: false

      - name: Generate code coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.25
        if: success() || failure()
        with:
          reports: build/reports/xml/jacoco
          targetdir: coveragereport
          reporttypes: MarkdownSummaryGithub
          sourcedirs: src/main/java
          title: 'Code Coverage'

      - name: Publish code coverage report as job summary
        if: success() || failure()
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      - name: Publish code coverage report as PR comment
        uses: madrapps/jacoco-report@v1.6.1
        if: github.event_name == 'pull_request' && (success() || failure())
        with:
          paths: |
            ${{ github.workspace }}/build/reports/xml/jacoco
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Coverage Report